### ISSUE TITLE
travis-ci builds are failing

### ISSUE THREAD

**Issue by kpdyer** [kpdyer/marionette#14]
Right now, travis-ci builds are failing because of https://github.com/kpdyer/marionette/commit/91b4ba224e132796a6dd9ea16b352850cf4449b2. It looks like we're returning the object from `unittest.TextTestRunner.run`, but we should be returning a proper return code.

**Comment by p1ck** [comment]
It should return a [TestResult](https://docs.python.org/2/library/unittest.html#unittest.TestResult) object.
So this should be looking at retcode.failures or retcode.errors instead.  Then of course retcode is a bad name for the object since it isn't a return code.

**Comment by p1ck** [comment]
Testing a fix here:  https://github.com/kpdyer/marionette/pull/15

**Comment by p1ck** [comment]
Resolved in #15 which returns `not TestResult.wasSuccessful()` as the exit code which should be 0 on success, and 1 for any other failure.

**Comment by p1ck** [comment]
@kpdyer You should also change your readme.md to point to your repo, not the redjack/marionette fork.

It is currently:  [![Build Status](https://travis-ci.org/redjack/marionette.svg?branch=master)](https://travis-ci.org/redjack/marionette)
`[![Build Status](https://travis-ci.org/redjack/marionette.svg?branch=master)](https://travis-ci.org/redjack/marionette)`

It should be:  [![Build Status](https://travis-ci.org/kpdyer/marionette.svg?branch=master)](https://travis-ci.org/kpdyer/marionette)
`[![Build Status](https://travis-ci.org/kpdyer/marionette.svg?branch=master)](https://travis-ci.org/kpdyer/marionette)`

It would be better to have one with a URL that is relative to the current fork, but that does not seem to be supported yet.  https://github.com/travis-ci/travis-ci/issues/779

**Comment by kpdyer** [comment]
Done. Thanks!
